services:
  proxy:
    restart: unless-stopped
    image: caddy:2.11-alpine
    ports:
      - 80:80
      - 3000:3000
    volumes:
      - ./docker/Caddyfile.dev:/etc/caddy/Caddyfile

  frontend:
    restart: unless-stopped
    build:
      dockerfile: ./docker/Dockerfile.dev.frontend
      context: .
    volumes:
      - ./frontend:/app
  
  backend:
    restart: unless-stopped
    build:
      dockerfile: ./docker/Dockerfile.dev.backend
      context: .
    volumes:
      - /usr/local/cargo
      - ./:/app
    env_file: .dev.env
    environment:
      PACKAGE: eduhost

  database:
    restart: unless-stopped
    build:
      dockerfile: ./docker/Dockerfile.dev.database
      context: .
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql
    env_file: .dev.env

  grafana:
    restart: unless-stopped
    image: grafana/grafana:12.3
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_LOG_LEVEL: error
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/etc/grafana/dashboards
      - ./data/grafana:/var/lib/grafana


  loki:
    restart: unless-stopped
    image: grafana/loki:3
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./docker/loki:/etc/loki
      - ./data/loki:/loki


