FROM node:25.6-alpine3.23 AS runner
WORKDIR /app

ENV CI=true


RUN npm install -g pnpm

COPY ./docker/frontend-entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

